### ISSUE TITLE
[ASK] - How to trigger loadOptions on first focus?

### ISSUE THREAD

**Issue by lamualfa-client** [rob-balfre/svelte-select#232]
I need to give some suggestions when the user first click the select component. How do i trigger `loadOptions` function in that state?

I use it for select component which contains a list of locations.

**Comment by rob-balfre** [comment]
Two different ways that I can think of...

https://svelte.dev/repl/53ca1599881e4deea7601e181397929f?version=3.20.1

**Comment by lamualfa-client** [comment]
Isn't there a way to show some suggestions taken from the `loadOptions` function?

Example like what Youtube did:

![image](https://user-images.githubusercontent.com/77015514/106413911-dad4c980-647d-11eb-8c2b-46fd2195eacb.png)

**Comment by rob-balfre** [comment]
Afraid not, there is no suggestion feature currently.

**Comment by raduab** [comment]
make a function const loadOptions = query => {...}

on the <Select /> you should add: loadOptions="{loadOptions}"

call the loadOptions at the end of the <script> tag like this:
const promise = loadOptions()

in the markup use the {#await promise} block

**Comment by taosx** [comment]
I'm doing something different, I'm having a fake mock for the select that is shown on the first render using an if block and when the user does a specific action I'm just changing it with the svelte-select and showing the actual thing with the items already loaded.
My usecase is a little different (each select except the first have a dependency on the previously selected state) here is the code:

```
{#each select_list as data}
    {#if !data.disabled}
        <div class="mt-4">
            <Select
                {optionIdentifier}
                {getOptionLabel}
                {getSelectionLabel}
                isDisabled={data.disabled}
                isClearable={true}
                placeholder={data.placeholder}
                items={data?.items}
                loadOptions={data.load_fn}
                isFocused={data?.focused}
                on:clear={console.log}
                on:select={data.handle_select}
            />
        </div>
    {:else}
        <div class="mt-4">
            <div class="px-4 py-2 border border-[#ebedef] text-sm text-[#c1c6cc] rounded-sm bg-[#ebedef]">
                <span class="h-[42px] leading-[1.5rem] ">{data.placeholder}</span>
            </div>
        </div>
    {/if}
{/each}
```

**Comment by V-Py** [comment]
Hi, just FYI, I ran into the same problem today, wanting to launch loadOptions function when clicking on the <Select />.
I used a simple trick which seems to do the job pretty well, ie fake launching with empty space (might work with something else).

`    <div class="whatever" on:click={handleClickOnSelect}>
        <Select {filterText} {listOpen} inputAttributes={inputAttributes} {groupBy} loadOptions={yourFunction} on:select={handleSelect} on:clear={handleClear} placeholder="Whatever" noOptionsMessage="No results" bind:this={$select}></Select>
    </div>`

`    async function handleClickOnSelect(){
        if(filterText) return;
        filterText = ' ';
    }`

Don't know if it's usefull, but since I ended on this issue during my researchs, thought I might share :)

**Comment by V-Py** [comment]
Hi, just FYI, I ran into the same problem today, wanting to launch loadOptions function when clicking on the . I used a simple trick which seems to do the job pretty well, ie fake launching with empty space (might work with something else). 


`async function handleClickOnSelect(){ if(filterText) return; filterText = ' '; } `
`<div on:click={handleClickOnSelect}><Select {filterText} loadOptions={yourFunction}/></div>`

Don't know if it's usefull, but since I ended on this issue during my researchs, thought I might share :)

**Comment by rob-balfre** [comment]
`suggestions` prop added in v5
