### ISSUE TITLE
Selecting options by mouse not working since 4.2.1

### ISSUE THREAD

**Issue by yadoga** [rob-balfre/svelte-select#278]
The merge from #264 introduced a bug, seemingly exposed not in Svelte but in SvelteKit apps: 

Selection of select options is no longer possible via mouse click!

I'm suspecting the deprecation of `handleWindowClick` in the `Svelte:window` listener to be the culprit. But that's only from a first glance…

**To replicate**
Set up a new SvelteKit app and add svelte-select. It will cease from working from 4.2.1 onwards.

Until fixed you could use 4.2.0.

**Comment by davidfou** [comment]
Setting the `tabindex` property to `'-1'` allows an element to have focus. This [line](https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/client/router.js#L152) of code is setting up that on the `body` by SvelteKit.

My assumption is when a user clicks on `div` to select an item, it removes the focus from the `input`. The consequence is, the `body` gets the focus and then the handler thinks the focus was lost.

Adding the same property on the root element of SvelteSelect component might do the trick as shown on this [demo](https://svelte.dev/repl/d297265fc2264f47a9165d1308682b27?version=3.38.3). When the focus is lost, instead of giving it to the `body`, the browser will give it to the first ancestor with the ability to be focusable (in that case, the root element).

Let me know if you think that explanation makes sense.

**Comment by yadoga** [comment]
Thanks, can confirm your finding to be working for me, too. Should this be something to notify the Svelte team about? And could this be implemented into svelte-selects latest version?

**Comment by davidfou** [comment]
It looks like to be much more normal behaviour from the browser. I'll work on a PR to cover that with a test. Let's see if @rob-balfre will be fine with that fix :crossed_fingers:

**Comment by rob-balfre** [comment]
has svelte-select@4.2.7-beta.1 fixed this?

**Comment by metayii** [comment]
> has svelte-select@4.2.7-beta.1 fixed this?

Not in my use case (npm updated all modules)

**Comment by rob-balfre** [comment]
@metayii whats your use case? 

I just created a fresh project with sveltejs/kit@1.0.0-next.132 and svelte-select@4.2.7-beta.1 and I'm no longer seeing this issue

**Comment by yadoga** [comment]
4.2.7-beta.1 fixed the issue on my end… 👍

**Comment by Zachiah** [comment]
I can confirm updating to 4.2.7-beta.1 fixed the issue for me as well. Thanks!

**Comment by rob-balfre** [comment]
v4.2.7 released.  Thanks all!
