### ISSUE TITLE
Incompatibility between using `loadOptions` and `isCreatable`

### ISSUE THREAD

**Issue by stephenlrandall** [rob-balfre/svelte-select#279]
REPL here: https://svelte.dev/repl/f8fdc3b73ffd4dbd85c61191284facf8?version=3.38.3.

When using custom `loadOptions`, the `isCreatable` prop seems to be ignored. The REPL compares current behavior to pre-v4 behavior.

I also noticed a separate issue while creating that REPL that I described; I think there may be an issue with how the loadOptions call is debounced when filterText becomes empty again.

**Comment by taosx** [comment]
I'm having a select that needs to both load options async and create new items and I'm hitting the same issue. I'm using an custom item component

**Comment by rob-balfre** [comment]
@stephenlrandall  and @taosx can you test svelte-select@4.2.7-beta.0 please

**Comment by taosx** [comment]
Just did, now I when I type and it's not found in the results from loadOptions it's showing in order to create but the actual function for creating isn't run. Also others selects started to break. I'll investigate and setup a demo.

off: I think it would be nice to start separating the library into core functionality and other derivations like creatable and async creatable similar to react-select. The state becomes really hard to track with all the features that you offer.

**Comment by rob-balfre** [comment]
@taosx thanks

> The state becomes really hard to track with all the features that you offer.

Yes 100%! Thats why there are 200+ tests. v4 was a big refactor to make it easier to track but there is still loads of room for improvement. If you want please feel free to make a seperate issue with some suggestions for improvements, I'd be interested to read your thoughts.

**Comment by stephenlrandall** [comment]
> @stephenlrandall and @taosx can you test svelte-select@4.2.7-beta.0 please

This still doesn't quite work for us, the custom item only appears when there are 0 matching items from the other options.

**Comment by rob-balfre** [comment]
@stephenlrandall how about svelte-select@4.2.7-beta.2 ?

**Comment by rob-balfre** [comment]
v4.2.7 released.  Reopen if it still doesn't work as expected. Thanks @stephenlrandall
