### ISSUE TITLE
How do I pass the attribute 'required' to the select input?

### ISSUE THREAD

**Issue by DesignMitZweiS** [rob-balfre/svelte-select#357]
I'm trying to pass the html attribute `required` to the select input by using `inputAttributes`.
However I don't know how to use it .. what's the correct syntax to pass the `required` attribute to it? Are there any docs?

**Comment by rob-balfre** [comment]
@DesignMitZweiS as Svelte-select isn't a true HTML input it wouldn't do anything. Better to handle in your own app.

**Comment by andreasnuesslein** [comment]
Well, it does work, kinda. `svelte-select` has a `<input>` field and it will have `required` upon `inputAttributes={{ required: true }}`  but svelte-select does not actually set the value of said input field when a value is selected. 

@rob-balfre what is your proposed solution so that it will behave similar to any other input field that is required? I.e. jump to the field and focus it, I mean.

Thanks :) And thanks for the package!

**Comment by andreasnuesslein** [comment]
https://github.com/rob-balfre/svelte-select/issues/167  just found this. I guess my question is moot. 

But it seems like, _some_ kind of solution would be nice (https://github.com/rob-balfre/svelte-select/issues?q=required) :D

**Comment by andreasnuesslein** [comment]
For anybody else looking for this: https://github.com/rob-balfre/svelte-select/issues/214#issuecomment-746589030
