### ISSUE TITLE
Select items on group search

### ISSUE THREAD

**Issue by pascal-kuschkowitz** [rob-balfre/svelte-select#404]
Is it possible to select items on group search with v5?

In this svelte [Repl v4](https://svelte.dev/repl/3e032a58c3974d07b7818c0f817a06a3?version=3.20.1), the search behavior works for everything except grouped items. I.e. the searched item is not selected when pressing enter (when searching for 'Chocolate' in the complex `select-field` and then pressing enter, the item is selected, but when doing the same in the group `select-field` the item is not getting selected.

**Comment by b3ngg** [comment]
![CleanShot 2022-05-05 at 09 18 16](https://user-images.githubusercontent.com/31965250/166878049-cc2c6586-93d0-4389-a676-18bc7867ef3b.gif)

It seems to me that is has something to do with the `isGroupHeaderSelectable` setting as seen in the example. 
When searching the `isGroupHeaderSelectable` probably doesn't get checked correctly so that the header is selected internally instead of the first item. 

Here's the REPL: https://svelte.dev/repl/4755fdc2817045fe99f0845140a64f30?version=3.20.1

**Comment by rob-balfre** [comment]
Should be fixed in latest beta?

https://svelte.dev/repl/242d533350d141f3b982e8ebeb229c53?version=3.49.0

**Comment by b3ngg** [comment]
Not really when searching “ice“ in the first input field and hitting enter nothing happens, although you would expect to select the “Ice Cream“ item. 

I got it fixed locally. I can do a PR.

**Comment by rob-balfre** [comment]
Should be all fixed in `5.0.0-beta.23` (reopen if not)

https://svelte.dev/repl/242d533350d141f3b982e8ebeb229c53?version=3.49.0
